dialogue open @e[type=npc,c=1] @a[scores={level=0}] Intro_1
dialogue open @e[type=npc,c=1] @a[scores={level=1}] Act_0
dialogue open @e[type=npc,c=1] @a[scores={level=2}] Act_0_Electrical
dialogue open @e[type=npc,c=1] @a[scores={level=3}] Act_1
dialogue open @e[type=npc,c=1] @a[scores={level=4}] Act_1_Bridge
dialogue open @e[type=npc,c=1] @a[scores={level=5}] Act_1_Card
dialogue open @e[type=npc,c=1] @a[scores={level=6}] Security_4
dialogue open @e[type=npc,c=1] @a[scores={level=7}] Act_1_Quarters
dialogue open @e[type=npc,c=1] @a[scores={level=8}] Act_2
dialogue open @e[type=npc,c=1] @a[scores={level=9}] Act_3
